services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5064

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes: # use host daemon
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5064:5064"
    environment:
      ConnectionStrings__DB: "Host=db;Port=5432;Database=restrictednl-db;Username=postgres;Password=postgres;"
      ConnectionStrings__Redis: "redis:6379"
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:7.2.7

  db:
    image: postgres:17.0
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: restrictednl-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d restrictednl-db"]
      interval: 5s
      timeout: 5s
      retries: 5
